### ISSUE TITLE
Node.js implementation

### ISSUE THREAD

**Issue by valdemon** [hootsuite/health-checks-api#6]
Hi,
at the beginning thanks for sharing your great work on microservices health check subject!

Here's the initial version of the __Node.js__ support: https://www.npmjs.com/package/healthchecks-api.
Evaluation, review and any feedback would be welcome!

Best regards

**Comment by HootAdam** [comment]
Hi @valdemon. Thanks. We will have a look and give the framework a try.

**Comment by HootAdam** [comment]
Hi @valdemon, I downloaded and ran the integration today and it seems to work well with the MGE which is great 😄. I was noticing something though that I am not sure I understand. It appears in the demo that `Service-2` shows up as a `WARN` on `http://localhost:9000/#/status/http/demo-app:3000` but when i navigate into `Service-2` at `http://localhost:9000/#/status/http/demo-app:3000/traverse/service-2` it appears as a `CRIT`. It seems like this is change in the way we report downstream failure as we don't change the value (ie `CRIT` to `WARN`) at the different levels.

**Comment by valdemon** [comment]
Hi Adam,
I've introduced aditional semantic of `not critical` service dependency. It's a configuration option for a service dependency, see: https://github.com/Bauer-Xcel-Media/node-healthchecks-api/blob/master/test/integration/conf/demo-app.yml#L25.
As a use case you can imagine an app, say an API gateway, which aggregates several services and when one which is not critical for the main business is down, I wouldn't like to report the whole App as CRIT (red) cause the main business can still be operating.
This is an option though, so one can use it or not.
Does it make sense for you?

**Comment by HootAdam** [comment]
Yeah I think this make sense for your use case and since it is an additional config, I don't see any harm. Is there any way you can highlight this more in the README as added functionality as it isn't in the spec?

I'm going to take a look more at the code and will also have a look at the service /status/... responses.

**Comment by valdemon** [comment]
It's actually already mentioned in https://www.npmjs.com/package/healthchecks-api#functionality. Maybe not highlighted enough, I'll add some code snippet there, or extend the spec of options a little bit.

**Comment by HootAdam** [comment]
Yeah I see it there, one thing I'd like to highlight is it is an implementation that is specific to this library, and not part of others. Just so people don't get confused and assume it is part of other language implementations.

**Comment by valdemon** [comment]
Ok, got the point. Will add that as soon as I'm at the keyboard. Currently writing to you with mobile ;)

**Comment by valdemon** [comment]
@HootAdam could you please check the note, before I'll publish a new version:
> **NOTE**
>
> _The `critical/non-critical` dependency atribute is an additional (optional) semantic of **this module  only**._
>
>_[Health Checks API](https://github.com/hootsuite/health-checks-api) does not specify such._
>
> _Classifying a particular dependency as `non-critical` (`critical: false` attribute of a dependency configuration) results in reporting it being in a `WARN` state at the dependency owner level, when the dependency is reported being in either `WARN` or `CRIT` state at its own level._
>
> _Example configuration for `non-critical` dependency:_
> ```yaml
> checks:
>   - name: service-2
>     critical: false
>     check: http
>     url: http://service-2:3002
> ```
> _By default all dependencies are classified as `critical`._

**Comment by HootAdam** [comment]
@valdemon Yes that looks great

**Comment by valdemon** [comment]
@HootAdam: Released in a meantime - https://www.npmjs.com/package/healthchecks-api

**Comment by valdemon** [comment]
Hi @HootAdam , thanks for the review!
Will explain/check/correct all these points hopefully in next hours (currently busy with my daily basis tasks).

Just a fast hint for the last point - please not that for now the module requires `nodejs >= 8.0.0`, which is set in the `package.json` and emphasized with the `REDADME.md` badge.
We could babelize the stuff when the support for previous node versions would be considered as a must, but, as you know, this brings a nice additional bunch of dependencies ;)

**Comment by valdemon** [comment]
@HootAdam - I've added you as a collaborator to the project, if you don't mind.
Please take a look to the linked PR which covers your listed above issues.
Once merged the new release will be created automatically in NPM.

**Comment by valdemon** [comment]
@HootAdam thanks again for the review. Released: https://www.npmjs.com/package/healthchecks-api/v/0.1.5

**Comment by HootAdam** [comment]
@valdemon Thanks :)
Here is the PR that adds your `Node` implementation to the list:
https://github.com/hootsuite/health-checks-api/pull/7

**Comment by valdemon** [comment]
Closing the issue. Pleasure to cooperate with you @HootAdam!
